#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"

MYSQL_OPTS="-u root"
MYSQL="mysql $MYSQL_OPTS"
MYSQLADMIN="mysqladmin $MYSQL_OPTS"

ldconfig

# Add to services
service findik on

function wait_for_mysqld() {
    /usr/share/findik/scripts/wait_for_mysqld
}

# If squid is installed and not running, start squid.
[ -n "$(service list|grep squid)" ] && \
	(service squid on; service squid start)

# If mysql-server is installed and not running, start mysql-server.
[ -n "$(service list|grep mysql_server)" ] && \
	(service mysql_server on; service mysql_server start)

wait_for_mysqld

pgrep mysqld > /dev/null ||
    (mysql_install_db; service mysql_server start)

wait_for_mysqld

# Import MySQL schema
if (echo|$MYSQL); then
	if [ -z "$(echo 'show databases'|$MYSQL|grep -e '^findik$')" ]; then
		( $MYSQLADMIN create findik && \
		$MYSQL findik < /usr/share/findik/sql/schema.sql ) || ( \
		echo "================================================="; \
		echo "|   A problem occured while importing schema.   |"; \
		echo "|   Please create a database and import         |"; \
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"; \
		echo "================================================="; \
		echo; )
	else
		echo "================================================="
		echo "|   A database named 'findik' exists on MySQL.  |"
		echo "|   Please create a database and import         |"
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Can not access MySQL.                       |"
	echo "|   Please create a database and import         |"
	echo "|   /usr/share/findik/sql/schema.sql manually.  |"
        echo "|   Also, edit MySQL credentials in             |"
	echo "|   /etc/findik/findik.cfg .                    |"
	echo "================================================="
	echo
fi

# Generating SSL keys.
if [ ! -f /etc/findik/ssl/public.pem -a ! -f /etc/findik/ssl/private.pem -a ! -f /etc/findik/ssl/dh.pem ]; then
	if (echo -e "ME\nRohan\nCalenardhon\nRohirrim\n\n*\nrohirrim@example.com\n"| \
		/usr/share/findik/scripts/generate-ssl-keys /etc/findik/ssl 512); then
		echo "================================================="
		echo "|   Created initial SSL keys and 512-byte DH    |"
		echo "|   parameters. If you want to recreate them,   |"
		echo "|   you can call                                |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "================================================="
		echo
	else
		echo "================================================="
		echo "|   A problem occured during key generation.    |"
		echo "|   Please recall and inspect output of         |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "|   command.                                    |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Found SSL keys at /etc/findik/ssl/ and      |"
	echo "|   kept unchanged. If you want to recreate     |"
	echo "|   them, you can call                          |"
	echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
	echo "================================================="
	echo
fi

service findik start

