#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"

MYSQL_OPTS="-u root"
MYSQL="mysql $MYSQL_OPTS"
MYSQLADMIN="mysqladmin $MYSQL_OPTS"

ldconfig

# Add to services
service findik on

## fetch a particular option from mysql's invocation
#
# usage: void mysqld_get_param option
mysqld_get_param() {
	/usr/sbin/mysqld --print-defaults \
		| tr " " "\n" \
		| grep -- "--$1" \
		| tail -n 1 \
		| cut -d= -f2
}

## Checks if there is a server running and if so if it is accessible.
#
# check_alive insists on a pingable server
# check_dead also fails if there is a lost mysqld in the process list
#
# Usage: boolean mysqld_status [check_alive|check_dead]
mysqld_status () {
    ping_output=`$MYSQLADMIN ping 2>&1`; ping_alive=$(( ! $? ))

    ps_alive=0
    pidfile=`mysqld_get_param pid-file`
    if [ -f "$pidfile" ] && ps `cat $pidfile` >/dev/null 2>&1; then ps_alive=1; fi
    
    if [ "$1" = "check_alive"  -a  $ping_alive = 1 ] ||
       [ "$1" = "check_dead"   -a  $ping_alive = 0  -a  $ps_alive = 0 ]; then
	return 0 # EXIT_SUCCESS
    else
  	return 1 # EXIT_FAILURE
    fi
}

function wait_for_mysqld() {
    for i in 1 2 3 4 5 6; do
        sleep 1
        if mysqld_status check_alive nowarn ; then break; fi
    done
}

# If squid is installed and not running, start squid.
[ -n "$(service list|grep squid)" ] && \
	(service squid on; service squid start)

# If mysql-server is installed and not running, start mysql-server.
[ -n "$(service list|grep mysql_server)" ] && \
	(service mysql_server on; service mysql_server start)

wait_for_mysqld

pgrep mysqld > /dev/null ||
    (mysql_install_db; service mysql_server start)

wait_for_mysqld

# Import MySQL schema
if (echo|$MYSQL); then
	if [ -z "$(echo 'show databases'|$MYSQL|grep -e '^findik$')" ]; then
		( $MYSQLADMIN create findik && \
		$MYSQL findik < /usr/share/findik/sql/schema.sql ) || ( \
		echo "================================================="; \
		echo "|   A problem occured while importing schema.   |"; \
		echo "|   Please create a database and import         |"; \
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"; \
		echo "================================================="; \
		echo; )
	else
		echo "================================================="
		echo "|   A database named 'findik' exists on MySQL.  |"
		echo "|   Please create a database and import         |"
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Can not access MySQL.                       |"
	echo "|   Please create a database and import         |"
	echo "|   /usr/share/findik/sql/schema.sql manually.  |"
        echo "|   Also, edit MySQL credentials in             |"
	echo "|   /etc/findik/findik.cfg .                    |"
	echo "================================================="
	echo
fi

# Generating SSL keys.
if [ ! -f /etc/findik/ssl/public.pem -a ! -f /etc/findik/ssl/private.pem -a ! -f /etc/findik/ssl/dh.pem ]; then
	if (echo -e "ME\nRohan\nCalenardhon\nRohirrim\n\n*\nrohirrim@example.com\n"| \
		/usr/share/findik/scripts/generate-ssl-keys /etc/findik/ssl 512); then
		echo "================================================="
		echo "|   Created initial SSL keys and 512-byte DH    |"
		echo "|   parameters. If you want to recreate them,   |"
		echo "|   you can call                                |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "================================================="
		echo
	else
		echo "================================================="
		echo "|   A problem occured during key generation.    |"
		echo "|   Please recall and inspect output of         |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "|   command.                                    |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Found SSL keys at /etc/findik/ssl/ and      |"
	echo "|   kept unchanged. If you want to recreate     |"
	echo "|   them, you can call                          |"
	echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
	echo "================================================="
	echo
fi

service findik start

